name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: podman build . --file standalone-trafficgen/Dockerfile-py3 --tag my-image-name:$(date +%s) \
           && podman pod create -p 50051:50051 -n trafficgen \
           && podman run -it --rm --privileged -v /dev:/dev -v /sys:/sys -v /lib/modules:/lib/modules --cpuset-cpus 12-23 -e pci_list=0000:81:00.0,0000:81:00.1 --pod trafficgen my-image-name:$(date +%s) /root/trafficgen_entry.sh server
